# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Farmacia Trafarm
town1: Orsova
email: trafarm@trafarm.ro
phone: "+40 252 363 480"
phone2: "+40 255 522 344"
description: Farmacia ta de incredere. Cea mai buna consiliere, cele mai bune recomandari # this means to ignore newlines until "baseurl:"

icons_folder: /assets/icons/
logo: /assets/images/logo.svg
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://www.trafarm.ro' # the base hostname & protocol for your site

image:
  facebook: /assets/images/logo.png

location: Trafarm
address: 1 Decembrie 1918, Orsova, Mehedinti, Romania
address2: Farmacie - Trafarm, Topleț

google_api_key: AIzaSyDU-T9LDgbnuQEUdUgeA4q63dFSQSwLhdM
google_site_verification: sf9mdjeJnbzFXPkXj01U3kMwm_IjHsZ_8aVjcI-47xw

# Build settings

markdown: kramdown

gems:
  - jekyll-seo-tag
