# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SC Trafarm SRL
town1: Orsova
email: trafarm@trafarm.ro
phone: "+40 252 363 480"
phone2: "+40 255 522 344"
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.trafarm.ro" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

location: Trafarm
address: 1 Decembrie 1918, Orsova, Mehedinti, Romania
address2: 1 Cearda, Toplet, Caras Severin, Topleț 327400, Romania

google_api_key: AIzaSyDU-T9LDgbnuQEUdUgeA4q63dFSQSwLhdM

gems:
  - jekyll-seo-tag
google_site_verification: sf9mdjeJnbzFXPkXj01U3kMwm_IjHsZ_8aVjcI-47xw
logo: img/header.jpg
